### ISSUE TITLE
Filename determination & handling

### ISSUE THREAD

**Issue by jlg89** [Owen-Cochell/PaperMC-Update#8]
I figured this was worth a new issue.

The readme is unclear on how the script determines the filename of the current PaperMC jar file.

My current workflow is to download the current version (at this moment paper-1.16.5-731.jar), softlink it to "paper.jar" and then reload the server. My startup script uses "paper.jar" so I don't have to update it every time, and using the softlink allows me to quickly check the installed version using a directory listing.

It sounds like, if I'm using your script, I could just eliminate the softlink, rename the downloaded jar to "paper.jar" and let your script handle the moving/renaming from there on out. I'll still need to follow up with a reload, but that's easy.

Am I reading the readme correctly?

**Comment by Owen-Cochell** [comment]
It's funny that you mention this, as I was working on the bug in the previous issue, I noticed the lack of clarity in specifying the file, and issues that could arise from supplying a directory instead of a path to a file.

As of right now, you must give the path to the jar file itself, just specifying the directory would not be enough. In your case, instead of giving './' to the script, you would give './paper.jar', or whatever the name of your jar file is currently. Your understanding is correct, if you rename the downloaded jar to something simple(like 'paper.jar'), and give the path to that file, then my script will handle the moving, deletion and backup of the jar file. If a new file is downloaded, then it will retain the name of the file it replaces. This ensures that your start file and my script will always be looking at the same file, regardless of the version. This would allow you to remove the softlink, as it would be unnecessary.

I agree with your assessment on the readme, it is unclear on how the filename would be specified. I'll be making some changes and additions that should make this more clear. I am also adding arguments that would allow the user to specify the target filename if just a directory is specified for the path, and to specify an output name that would be used instead of the old name. If an old name is not specified via argument or path, then the downloaded file will not be renamed.

Hope this clears some things up. Let me know if this is still not clear or you notice any more issues with file naming. I'll reference this issue in the commit that adds these arguments and fixes up the readme, and i'll leave another comment here. If the changes are to your liking then i'll close this issue.

Thanks!

**Comment by jlg89** [comment]
Re-reading the readme with all this in mind, it makes more sense now. I think the clarification and additional arguments will definitely help.

**Comment by Owen-Cochell** [comment]
Should be a bit more clear on how to specify files/locations to update, and how the script determines the output filename.

If the readme and options look good then I will close this issue.

**Comment by jlg89** [comment]
Beautiful and useful work. Thanks for the labor of love.
